# apiVersion: v1
# kind: Namespace
# metadata:
#   name: {{ .Values.operators.gitops.namespace }}
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: redhat-ods-applications

apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat OpenShift Serverless"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-serverless

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: serverless-operator-group
  namespace: openshift-serverless

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "NVIDIA GPU Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: nvidia-gpu-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
spec:
  targetNamespaces:
    - nvidia-gpu-operator
---

apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Node Feature Discovery Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-nfd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  targetNamespaces:
    - openshift-nfd
---
